version: '3.4'

services:
  ecommerce.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"

  ecommerce.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6003:80"

  ecommerce.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"


  ecommerce.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6004:80"
    environment:
      - Services__Products=http://ecommerce.api.products
      - Services__Customers=http://ecommerce.api.customers
      - Services__Orders=http://ecommerce.api.orders

